# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  web:
    # The build parameters for this container.
    environment:
      APP_PORT: ${APP_PORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ALEXA_SKILL_ID: ${ALEXA_SKILL_ID}
    build:
      # Here we define that it should build from the current directory
      context: .
    ports:
    # Mapping the port to make the Phoenix app accessible outside of the container HOST:CONTAINER
      - ${APP_PORT}:${APP_PORT}
    image: alexfilatov/chuck:latest
