version: '3.1'

services:
  web:
    image: chuck_web:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      APP_HOSTNAME: ${APP_HOSTNAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
